### ISSUE TITLE
Knowledge base

### ISSUE THREAD

**Issue by ghermans** [salesagility/SuiteCRM-Portal-Joomla#2]
# Description

It would be nice if the knowledge base should be integrated in the portal.
# Suggestions
- Create index view where articles are published in groups (KB_categories)
- Add search textfield on the portal kb page.
- Extra feature: rate article, so a company knows if the article was helpful or not.

**Comment by boombata** [comment]
Hi, 

It is included in 3beta branch.

Regards,
BM
