### ISSUE TITLE
AOP versions and released files

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM-Portal-Joomla#20]
@mattlorimer @JimMackin Please consider to update the files available for download on SuiteCRM site. The version uploaded is dated from 2013 and has you can imagine this is a bad sign for webmasters considering that.
Then again this is not the latest version available, its just the one available to be download from the SuiteCRM site.

Those are the versions:
- Version 1.1.1 (July 2013) => the latest file available to public download at suiteCRM site https://suitecrm.com/download/suitecrm-joomla-plug-in
- Version 2.0.1 (October 2015) => the Master on Github. But there is no released file on github and no download file on SuiteCRM site. Note that there are some PR to version 2.x waiting to be merge (mostly on translations)
- Version 3.0.0 Beta (November 2016) => not for productions sites, under work since November 2016 (branch 3beta )

Also please consider to list this extension at JED Joomla! Extensions Directory - https://extensions.joomla.org
This is where all users start looking into extensions and is the most visited Joomla.org site. So you are loosing an incredible amount of product and company visibility.

**Comment by Dillon-Brown** [comment]
No longer an issue.
