### ISSUE TITLE
AOP File attachment empty

### ISSUE THREAD

**Issue by jcmoreno8** [salesagility/SuiteCRM-Portal-Joomla#23]
Hello,
I setup Suitecrm on local server in a customer with AOP

I can use the portal as user after created an acccount.

But when I create a ticket on the portal, if I attach a file with the message, no files appears on the portal and in the CRM the case is well created, contains the name of the attachment, linked with the ticket but does not contains any file.

Somebody could help me to solve this problem or give me ideas, I would be very grateful !

**Comment by Dillon-Brown** [comment]
Hi @jcmoreno8, please post general AOP issues in the community forum https://suitecrm.com/forum/advanced-opensales-workflow-portal-support and leave GitHub for core issues only. Thanks
