### ISSUE TITLE
Installation Issues: ZIP Error(0): Status(9)

### ISSUE THREAD

**Issue by ruslanguns** [salesagility/SuiteCRM-Portal-Joomla#27]
I have downloaded the Git, unziped and then zipped again with 7zip the proper files, and getting `ZIP Error(0): Status(9): `

My version is:
> Versión 7.8.3 
> Sugar Versión 6.5.24 (Compilación 509)

Please let me know if you guys have any solution for this issue. Thanks in advance

**Comment by horus68** [comment]
This is not a proper GIT issue. You should post a question in forum here:
https://suitecrm.com/forum/advanced-opensales-workflow-portal-support

Please close your GIT issue
